server:
  port: 7902
spring:
  application:
    name: micro-auth
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql:///test?serverTimezone=UTC
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
